### ISSUE TITLE
Polyline won't rerender

### ISSUE THREAD

**Issue by abigreenlizard** [fullstackreact/google-maps-react#242]
Hi, this issue has been driving me mad for days, really hope someone can provide a solution.

Here is a snippet from my MapContainer render method:

```  return (
      <div>
        <Map
          google={this.props.google}
          className="map"
          zoom={12}
          gestureHandling={"cooperative"}
          initialCenter={{
            lat: 53.3498,
            lng: -6.2603
          }}
        >
          <Polyline
            fillColor="#0000FF"
            fillOpacity={0.35}
            path={this.state.polylineCoordinates}
            strokeColor="#0000FF"
            strokeOpacity={0.8}
            strokeWeight={2}
          />
```
I have some test coordinates defined:

```
const testCoords = [
      { lat: 53.378, lng: -6.057 },
      { lat: 53.378, lng: -6.056 },
      { lat: 53.378, lng: -6.056 }
    ];
```
When I pass testCoords to the path of the Polyline component, it works fine. However, when I change the value being passed to ``path`` dynamically, the polyline disappears. I also noticed that it disappears on any map-rerender. So when I draw markers or do something unrelated to the Polyline that causes a map-rerender, the Polyline disappears. I've checked that the path property is being passed a suitably formatted array of objects, structured exactly the same as the testCoords var above. I've also confirmed that Polyline has the properties I expect using the react developer tools.

Any hints in the right direction would be much appreciated.

**Comment by abigreenlizard** [comment]
Made a stupid mistake passing props, nm thanks.

**Comment by zachfejes** [comment]
Hey, just for anyone having a similar problem in future:

I've been dealing with a similar problem for several days, and finally discovered that the props we were passing to the Polyline (specifically the `path` parameter) was being used incorrectly.

Specifically, our `path` parameter was stored in our component's `state`, and then passed to the Polyline component for rendering. We also included a method to alter an element in the `path` array. However, in this modification, we accidentally modified the state object itself, and then called `this.setState()` to update it. Because our change effected the state immediately, that parameter was passed to the Polyline, and when the `setState` triggered a re-render, the Polyline checked its new props against its old, but the old had already updated along with the state.

The fix was to create a copy of the state variable, modify that copy, and then call `this.setState()` with the copy so that we only updated the state once, and in the sequence we expect.

Hopefully that helps!
