### ISSUE TITLE
Google Maps JavaScript API multiple times on this page

### ISSUE THREAD

**Issue by LuizGMiranda** [fullstackreact/google-maps-react#284]
Hi,

I have been the necessity of has a in my browser head, how I do?

Html in head:
<script src="https://maps.googleapis.com/maps/api/js?[_MY_KEY_]&amp;callback=myFunction"></script>

**Comment by auser** [comment]
You should be able to use the wrapper directly without using the google maps shim

**Comment by wdevon99** [comment]
> Ok never mind, I understood what you meant. There is no need to use `GoogleApiWrapper` which I was using. :)

Yes! We can access the google object from the window object if we load the script separaetly

**Comment by Asuddle** [comment]
Hello there , I am getting the same issue as mentioned above . I am using the google-maps-react to render map and using react-geosuggest library for populating google places autocomplete field.I have added the  script in head html 

<script src="https://maps.googleapis.com/maps/api/js?[_MY_KEY_]&libraries=places"></script> 

and experiencing the same error 
"You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors."

I tried removing GoogleApiWrapper and it doesn't load the google map. What can I do for handling it ?

**Comment by felixmeziere** [comment]
same here! What can I do? Not clear from the above.

**Comment by felipenmoura** [comment]
It does work by using the `window.google` instead of the wrapper, but I still get the error message for loading the API multiple times!
I **DON'T WANT** it to be loaded in the wrapper or the component, because I have the scripts for loading the api (and other important things related to the maps api) somewhere else.

Is there a way to avoid this component from loading its own version of the maps api?

**Comment by Palaklive** [comment]
Try with [google-map-react](https://github.com/google-map-react/google-map-react) it'll solve the issue.
