### ISSUE TITLE
Publish v1.0.20?

### ISSUE THREAD

**Issue by mruoss** [fullstackreact/google-maps-react#84]
I can see this library being maintained, but there has not been a release for 7 months now. Do you have a release plan? Can you let us know, when the next version will be released?
Thanks, Michael

**Comment by thienanle** [comment]
+1

The current version on npm still doesn't support passing options as `false` (if falsey, the option is deleted before map initialize), though the src has had it fixed for some time.

**Comment by lucmerceron** [comment]
👍 

I would love to have a v1.0.20 on npm so depreciation warnings (PropTypes) would disappear. It is currently spamming my browser and test consoles.

**Comment by ryanjones71** [comment]
What does it take to get a build pushed to NPM?  Is it anything that we can help with?  I've been looking at the source here because it's easier to read than the packaged code and today I just realized that I've been bit by a couple of bugs/differences in the code base.  V1.0.20 would be much appreciated.

**Comment by auser** [comment]
I pushed a new version `v1.1.0`. :)

**Comment by mruoss** [comment]
Thank you very much @auser !! Is there a changelog somewhere by any chance?
